version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: ["npm", "start"]

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    command: ["node", "server.js"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
